### PR TITLE
LRDOCS-9615 & LRDOCS-9619 Message Boards API Code

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR includes code samples for `MessageBoardSection`, `MessageBoardThread`, and `MessageBoardMessage`, in fulfillment of [LRDOCS-9615](https://issues.liferay.com/browse/LRDOCS-9615) and [LRDOCS-9619](https://issues.liferay.com/browse/LRDOCS-9619). While this material was originally divided between two tickets, it seemed better to combine them together, since they're closely related entities. That said, if you think they should be divided, just let me know!

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
@jhinkey Just noticed some errors in naming. Fixing and will update PR.

**Comment by jhinkey** [comment]
Sounds good, James. Thanks.

**Comment by JamesAGarcia** [comment]
@jhinkey I updated the PR, but I should say: I didn't get either the PUT command to work for the `MessageBoardMessage` service--both the cURL and java calls return a server error. Would you like me to contact the headless team about it, or would you like to take a look at it first to see if I've made a simple mistake?

Also, while the `java` POST and PATCH commands work for the `MessageBoardMessage` service, it returns a `java.lang.IllegalArgumentException`. Does that seem like a bug, or have I done something wrong?

As always, thank you for your time and input, Jim!

**Comment by JamesAGarcia** [comment]
@jhinkey  
Update: Makoto discovered why the PUT commands weren't working for `MessageBoardMessage`. It appears that the `showAsAnswer` field is required...which seems odd, and may be a bug? I've asked the Headless team about it [here](https://liferay.slack.com/archives/C5E1CRLJY/p1631246647043700). 

I also asked the Headless team about the exception message [here](https://liferay.slack.com/archives/C5E1CRLJY/p1631248211046300).

**Comment by jhinkey** [comment]
Thanks, James. I'm starting to review it now.

**Comment by jhinkey** [comment]
Sorry for the delayed response. I've been tied up with adding to and reviewing the 7.4 breaking changes doc in liferay-portal, and creating a much needed map of renamed language keys (a result of the language key consolidation).

**Comment by jhinkey** [comment]
Please resend after addressing the review comments. Thanks, James.

**Pull request closed without merging**
