### PR TITLE
LRDOCS-7746 Custom Order Engine Status Implementation

### PR DESCRIPTION
**Pull request by aswinrajeevofficial**
This PR contains the code for LRDOCS-7746 which implements a custom order status in the Commerce Order Engine. 

The new status is called 'Scheduling' and it will be placed between the current 'Pending' and 'Processing' statuses.

https://issues.liferay.com/browse/LRDOCS-7746

### CODE REVIEW

**Comment by jhinkey** [comment]
Started reviewing. Thanks, Aswin.

**Comment by jhinkey** [comment]
@aswinrajeevofficial - A few questions.

1. What is the status sequence this demonstrates? Is it pending > scheduling > processing or processing > scheduling > pending?
2. Why did you have to implement another processing status?

Thanks

**Comment by aswinrajeevofficial** [comment]
Hi @jhinkey 

1. The sequence is demonstrating the following:
Pending -> Scheduling -> Processing (the priorities depict the order. Pending (30), Scheduling (40), Processing (50))

2. Every order status has a transition criteria (which ensures it is correctly coming into the status), an action (which is performed after it transitions) and a completion step (which is a check to confirm whether status is complete)
Since I added the new status in between Pending and Processing, the Processing logic needed to check for the new status, instead of the old one. The entire logic inside it remains the same except for the fact that it is now checking whether the order was previously in 'Scheduling' so that it can transition to 'Processing'.

**Comment by jhinkey** [comment]
Merged locally. Thanks.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-learn/pull/321

**Pull request closed without merging**
