### PR TITLE
LRDOCS-9606 StructuredContents curl scripts

### PR DESCRIPTION
**Pull request by jorge-campo**
This PR proposes the scripts for the GET, POST, PATCH, PUTH, and DELETE methods in the structured-contents service (Headless delivery.) This is requested in [LRDOCS-9606](https://issues.liferay.com/browse/LRDOCS-9606).

~~*Note:* The `POST` method requires at least one parameter for each `contentFieldValue` in the Structure (parameters `${3}` and `${4}` in my example.) Liferay DXP assigns this value when we create a new Structure. However, because we can't create a Structure programmatically using the REST API and assign a value beforehand, the only way to check the value is after the user creates the Structure in the GUI. In other words, we can't know in advance the `contentFieldValue` for a Structure; therefore, we need to check that value manually and pass it to the scripts as a parameter, along with the Site ID (`${1}`) and Web Content ID (`${2}`).~~

Update 29.Jul.21:

- I updated the cURL scripts on this PR following @mtokudome 's suggestions.
- The markdown article for this content is included in a different PR: https://github.com/jhinkey/liferay-learn/pull/94

### CODE REVIEW

**Comment by mtokudome** [comment]
Hey @jorge-campo, since Jim is on PTO, I thought I could help and give some suggestions on this. So your GET and DELETE scripts look great. For your POST script, a few suggestions:
* The arguments in the script should be in alphabetical order (first uppercase and then lowercase) (e.g. -H, -X, -d, -u)
* You can do it manually but I think you should also run sourceFormat on the script so that you have the proper backslashes on your parameters.
* Pay attention to the shell filenames. The GET script should be plural since your getting multiple structuredcontents from Site, but the POST and DELETE should be singular (e.g. `StructuredContent_DELETE_FromSite.sh` and not `StructuredContents_DELETE_FromSite.sh`)
* From my understanding, Brian tends to like very minimal code where if an argument is not required then it should probably be omitted. I was playing around with the POST extension and found that you really only need `title` and `contentStructureId`). You can try, but this seems to work for me:

```
curl \
	-H "Content-Type: application/json" \
	-X POST \
	"http://localhost:8080/o/headless-delivery/v1.0/sites/${1}/structured-contents" \
	-d "{\"title\": \"Foo\", \"contentStructureId\": \"${2}\"}" \
	-u "test@liferay.com:test"
```

**Comment by mtokudome** [comment]
The next two scripts would be the PATCH and PUT shell files. You can take a look at my Blog example of how I am changing the `articleBody` from Foo (POST) to Bar (PATCH) to GOO (PUT) and keeping the same headline. You could probably do the same with your `title`: https://github.com/liferay/liferay-learn/tree/master/docs/dxp/latest/en/content-authoring-and-management/blogs/developer-guide/blog-api-basics/resources/liferay-r3g4.zip/curl

**Comment by jorge-campo** [comment]
Hi @mtokudome - Thanks for your comments.

I see what you mean about trying to err on the minimalistic side with code. A simple and minimal curl script can be more beneficial than a more complex one to understand **the basics**. However, if we are too simplistic on the examples we provide, I'm not sure about the article's value for developers looking **beyond the basics**. Finding the complete POST example on my PR took me several hours of research; this is precisely the type of thing I want to save developers reading my article. 

Maybe we can try to find balance, including a simple example and a more elaborated one. However, including an elaborated example with multiple parameters is still valuable when you need something other than a basic POST script.

**Comment by jhinkey** [comment]
Started reviewing. Thank you.

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-learn/pull/258. Thanks.

**Comment by jhinkey** [comment]
@jorge-campo @mtokudome - I updated the scripts to add content (HTML). This required passing in a set of `contentField`s. Please see the changes I made. Thanks!

**Comment by jorge-campo** [comment]
Superseded by https://github.com/jhinkey/liferay-learn/pull/98.

**Pull request closed without merging**
