### PR TITLE
LRDOCS-7774 Code

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-7774

Instead of an example using a multi-parameter language key, I added an aui-validator for an email validation example. Let me know what you think.

### CODE REVIEW

**Comment by jhinkey** [comment]
Reviewing now. Thanks.

**Comment by jhinkey** [comment]
The portlet content isn't rendering localized for me. Can you test on your end?

tmp-localized-app-pt-br

**Comment by mtokudome** [comment]
@jhinkey I added back a file I deleted last night. It should work now.

**Comment by jhinkey** [comment]
Thanks!

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-learn/pull/144

**Pull request closed without merging**
