### PR TITLE
LRDOCS-9147 Code for 'Organize Fragment Tree Information' developer tutorial

### PR DESCRIPTION
**Pull request by jorge-campo**
This is the code review task for the upcoming "Setting the Order of Elements in a Fragment" developer tutorial (see parent Jira ticket [LRDOCS-8915](https://issues.liferay.com/browse/LRDOCS-8915)).

The tutorial will discuss:
 - The new `data-lfr-priority` HTML attribute in Liferay DXP 7.4+ for Slider or Tab Fragments.
 - How to import a sample Slider Fragment from Liferay DXP 7.3 into DXP 7.4 (*this task contains the sample Slider Fragment code.*)
 - How to update the sample Fragment code using the `data-lfr-priority` HTML attribute to set the order of elements in a Fragment.
 - How to verify the new order of elements in the sample Slider Fragment.

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi @jorge-campo ,

I'll review your branch after its done SME review. When your code is done SME review, please force push any changes to this branch and let me know. 

Thanks

**Comment by jhinkey** [comment]
Starting review. Thanks.

**Comment by jhinkey** [comment]
@jorge-campo Can you resend the code unzipped? I was expected the liferay-xxxx.zip folder to be something like this [one](https://github.com/liferay/liferay-learn/tree/master/docs/dxp/7.x/en/site-building/developer-guide/developing-page-fragments/adding-configuration-options-to-fragments/resources/liferay-c7f8.zip). Thanks. :-)

**Comment by jorge-campo** [comment]
Superseded by https://github.com/jhinkey/liferay-learn/pull/54

**Pull request closed without merging**
