### PR TITLE
LRDOCS-7770 Code

### PR DESCRIPTION
**Pull request by mtokudome**
https://issues.liferay.com/browse/LRDOCS-7770

### CODE REVIEW

**Comment by jhinkey** [comment]
Reviewing now. Thanks.

**Comment by jhinkey** [comment]
Reviewing now. Thanks.

**Comment by mtokudome** [comment]
@jhinkey I forgot to add the `"javax.portlet.supported-locale=en_US,ja,pt_BR",` line in the component property but was surprised to see that it still works without it

**Comment by jhinkey** [comment]
Also, would you sort each Language* file's keys?

**Comment by jhinkey** [comment]
Sent https://github.com/brianchandotcom/liferay-learn/pull/148 Thanks

**Pull request closed without merging**
